/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetTileSizeDialog.java
 *
 * Created on 2011-6-1, 9:34:43
 */
package com.soyostar.editor.map.dialog;

import java.awt.Rectangle;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SetTileSizeDialog extends javax.swing.JDialog {

    /** Creates new form SetTileSizeDialog
     * @param parent 
     * @param modal 
     */
    public SetTileSizeDialog(EditTileDialog parent, boolean modal) {
        super(parent, modal);
        tscd = parent;
        initComponents();
        initialize();
    }
    private EditTileDialog tscd;

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tileWidthSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tileHeightSlider = new javax.swing.JSlider();
        cancleButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        sizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(SetTileSizeDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        tileWidthSlider.setMajorTickSpacing(16);
        tileWidthSlider.setMaximum(128);
        tileWidthSlider.setMinorTickSpacing(1);
        tileWidthSlider.setPaintLabels(true);
        tileWidthSlider.setPaintTicks(true);
        tileWidthSlider.setSnapToTicks(true);
        tileWidthSlider.setValue(32);
        tileWidthSlider.setName("tileWidthSlider"); // NOI18N
        tileWidthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tileWidthSliderStateChanged(evt);
            }
        });

        jLabel1.setText("宽度");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("高度");
        jLabel2.setName("jLabel2"); // NOI18N

        tileHeightSlider.setMajorTickSpacing(16);
        tileHeightSlider.setMaximum(128);
        tileHeightSlider.setMinorTickSpacing(1);
        tileHeightSlider.setPaintLabels(true);
        tileHeightSlider.setPaintTicks(true);
        tileHeightSlider.setSnapToTicks(true);
        tileHeightSlider.setValue(32);
        tileHeightSlider.setName("tileHeightSlider"); // NOI18N
        tileHeightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tileHeightSliderStateChanged(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        sizeLabel.setText("当前大小："+tileWidthSlider.getValue()+"*"+tileHeightSlider.getValue());
        sizeLabel.setName("sizeLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                        .addComponent(cancleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tileWidthSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tileHeightSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                    .addComponent(sizeLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tileWidthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tileHeightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sizeLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        tscd.setBound(new Rectangle(tileWidthSlider.getValue(), tileHeightSlider.getValue()));
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void tileWidthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tileWidthSliderStateChanged
        // TODO add your handling code here:
        sizeLabel.setText("当前大小："+tileWidthSlider.getValue()+"*"+tileHeightSlider.getValue());
        sizeLabel.repaint();
    }//GEN-LAST:event_tileWidthSliderStateChanged

    private void tileHeightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tileHeightSliderStateChanged
        // TODO add your handling code here:
        sizeLabel.setText("当前大小："+tileWidthSlider.getValue()+"*"+tileHeightSlider.getValue());
        sizeLabel.repaint();
    }//GEN-LAST:event_tileHeightSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SetTileSizeDialog dialog = new SetTileSizeDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JSlider tileHeightSlider;
    private javax.swing.JSlider tileWidthSlider;
    // End of variables declaration//GEN-END:variables
}
