/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PluginManagerDialog.java
 *
 * Created on 2011-3-15, 13:57:26
 */
package com.soyostar.editor.dialog;

import com.soyostar.editor.map.main.AppData;
import com.soyostar.editor.plugin.Plugin;
import com.soyostar.editor.plugin.PluginLoader;
import com.soyostar.editor.util.Log;
import java.awt.Desktop;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class PluginManagerDialog extends javax.swing.JDialog {

    /** Creates new form PluginManagerDialog
     * @param parent 
     * @param modal 
     */
    public PluginManagerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
        initPluginTable();
    }

    private void initialize() {
        setLocationRelativeTo(null);
    }
    private ArrayList<Plugin> plugins = new ArrayList<Plugin>();

    private void initPluginTable() {
        try {
            plugins = PluginLoader.getInstance().getPlugins();
            for (int i = 0, n = plugins.size(); i < n; i++) {
                String[] data = {plugins.get(i).getName(), plugins.get(i).getAuthor(), plugins.get(i).getVersion()};
                pluginTableModel.addRow(data);
            }
        } catch (Exception e) {
            Log.getLogger(this.getClass()).error("初始化插件信息异常！", e);
        }

    }
    private String[] col = {"名称", "作者", "版本"};
    private DefaultTableModel pluginTableModel = new DefaultTableModel(col, 0) {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pluginTable = new javax.swing.JTable();
        infoButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        morePluginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(PluginManagerDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        pluginTable.setModel(pluginTableModel);
        pluginTable.setName("pluginTable"); // NOI18N
        pluginTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pluginTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pluginTable);

        infoButton.setText("详细");
        infoButton.setName("infoButton"); // NOI18N
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        closeButton.setText("关闭");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        morePluginButton.setText("更多插件");
        morePluginButton.setName("morePluginButton"); // NOI18N
        morePluginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morePluginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(83, 83, 83)
                .addComponent(morePluginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(87, 87, 87)
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoButton)
                    .addComponent(closeButton)
                    .addComponent(morePluginButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void morePluginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morePluginButtonActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("http://www.soyostar.com/forum.php?mod=forumdisplay&fid=77").toURI());
        } catch (Exception e) {
            Log.getLogger(this.getClass()).error("打开软件首页异常！", e);
        }
    }//GEN-LAST:event_morePluginButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        // TODO add your handling code here:
        if (!plugins.isEmpty()) {
            if (pid == null) {
                pid = new PluginInfoDialog();
            }
            pid.pluginInfoTextArea.setText(plugins.get(curRow).getDescription());
            pid.setVisible(true);
        }
    }//GEN-LAST:event_infoButtonActionPerformed
    private int curRow = -1;
    private PluginInfoDialog pid;
    private void pluginTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pluginTableMouseClicked
        // TODO add your handling code here:
        curRow = pluginTable.getSelectedRow();
        if (!plugins.isEmpty() && evt.getClickCount() >= 2) {
            if (pid == null) {
                pid = new PluginInfoDialog();
            }
            pid.pluginInfoTextArea.setText(plugins.get(curRow).getDescription());
            pid.setVisible(true);
        }
    }//GEN-LAST:event_pluginTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PluginManagerDialog dialog = new PluginManagerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton morePluginButton;
    private javax.swing.JTable pluginTable;
    // End of variables declaration//GEN-END:variables
}
