/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferenceDialog.java
 *
 * Created on 2011-5-8, 1:17:08
 */
package com.soyostar.editor.dialog;

import com.soyostar.editor.config.Configuration;
import com.soyostar.editor.map.main.AppData;
import com.soyostar.editor.util.Log;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Administrator
 */
public class PreferenceDialog extends javax.swing.JDialog {

    /** Creates new form PreferenceDialog
     * @param parent 
     * @param modal 
     */
    public PreferenceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rightEraserCheckBox.setSelected(Configuration.getIsRightEraser());
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        rightEraserCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uiTable = new javax.swing.JTable();
        cancleButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(PreferenceDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        setTabbedPane.setName("setTabbedPane"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        rightEraserCheckBox.setText("开启右键橡皮功能 (勾选后绘图时，右键按下也视为擦除)");
        rightEraserCheckBox.setName("rightEraserCheckBox"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rightEraserCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rightEraserCheckBox)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        setTabbedPane.addTab("设置", jPanel2);

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        uiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Integer(1), "Autumn"},
                {new Integer(2), "BusinessBlackSteel"},
                {new Integer(3), "BusinessBlueSteel"},
                {new Integer(4), "Business"},
                {new Integer(5), "ChallengerDeep"},
                {new Integer(6), "Creme"},
                {new Integer(7), "CremeCoffee"},
                {new Integer(8), "Dust"},
                {new Integer(9), "DustCoffee"},
                {new Integer(10), "EmeraldDusk"},
                {new Integer(11), "Gemini"},
                {new Integer(12), "GraphiteAqua"},
                {new Integer(13), "GraphiteGlass"},
                {new Integer(14), "Graphite"},
                {new Integer(15), "Magellan"},
                {new Integer(16), "Mariner"},
                {new Integer(17), "MistAqua"},
                {new Integer(18), "MistSilver"},
                {new Integer(19), "Moderate"},
                {new Integer(20), "NebulaBrickWall"},
                {new Integer(21), "Nebula"},
                {new Integer(22), "OfficeBlack2007"},
                {new Integer(23), "OfficeBlue2007"},
                {new Integer(24), "OfficeSilver2007"},
                {new Integer(25), "Raven"},
                {new Integer(26), "Sahara"},
                {new Integer(27), "Twilight"}
            },
            new String [] {
                "编号", "皮肤名称"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uiTable.setName("uiTable"); // NOI18N
        uiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(uiTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setTabbedPane.addTab("外观", jPanel1);

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(setTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(setTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancleButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Configuration.saveIsRightEraser(rightEraserCheckBox.isSelected());
        if (uiTable.getSelectedRow() != -1) {
            Configuration.setSkin("org.pushingpixels.substance.api.skin.Substance" + uiTable.getModel().
                getValueAt(uiTable.getSelectedRow(), 1).toString() + "LookAndFeel");
        }
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void uiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiTableMouseClicked
        // TODO add your handling code here:

//        System.out.println(uiTable.getModel().getValueAt(uiTable.getSelectedRow(), 1).toString());
        try {
            UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.Substance" + uiTable.getModel().
                getValueAt(uiTable.getSelectedRow(), 1).toString() + "LookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);//更新控件的外观
        } catch (Exception e) {
            System.out.println("不支持的皮肤");
        }
    }//GEN-LAST:event_uiTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PreferenceDialog dialog = new PreferenceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox rightEraserCheckBox;
    private javax.swing.JTabbedPane setTabbedPane;
    private javax.swing.JTable uiTable;
    // End of variables declaration//GEN-END:variables
}
